version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: social-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  web:
    image: distributed-social-network:latest
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/social-network
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

volumes:
  postgres_data:
    driver: local

networks:
  default:
    driver: overlay
