# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chord.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chord.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\x12\x05\x63hord\"\x07\n\x05\x45mpty\"\x10\n\x02ID\x12\n\n\x02id\x18\x01 \x01(\x04\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\t\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\'\n\x08NodeInfo\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t2\xaf\x02\n\x0c\x43hordService\x12+\n\rFindSuccessor\x12\t.chord.ID\x1a\x0f.chord.NodeInfo\x12/\n\x0eGetPredecessor\x12\x0c.chord.Empty\x1a\x0f.chord.NodeInfo\x12\x32\n\x11UpdatePredecessor\x12\x0f.chord.NodeInfo\x1a\x0c.chord.Empty\x12\"\n\x04Ping\x12\x0c.chord.Empty\x1a\x0c.chord.Empty\x12$\n\x03Put\x12\x0f.chord.KeyValue\x1a\x0c.chord.Empty\x12\x1f\n\x03Get\x12\n.chord.Key\x1a\x0c.chord.Value\x12\"\n\x06\x44\x65lete\x12\n.chord.Key\x1a\x0c.chord.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chord_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_ID']._serialized_start=31
  _globals['_ID']._serialized_end=47
  _globals['_KEY']._serialized_start=49
  _globals['_KEY']._serialized_end=67
  _globals['_VALUE']._serialized_start=69
  _globals['_VALUE']._serialized_end=91
  _globals['_KEYVALUE']._serialized_start=93
  _globals['_KEYVALUE']._serialized_end=131
  _globals['_NODEINFO']._serialized_start=133
  _globals['_NODEINFO']._serialized_end=172
  _globals['_CHORDSERVICE']._serialized_start=175
  _globals['_CHORDSERVICE']._serialized_end=478
# @@protoc_insertion_point(module_scope)
