# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chord.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chord.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\x12\x05\x63hord\"\x07\n\x05\x45mpty\"\x14\n\x06NodeId\x12\n\n\x02id\x18\x01 \x01(\x04\"\'\n\x08NodeInfo\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"*\n\x08NodeList\x12\x1e\n\x05nodes\x18\x01 \x03(\x0b\x32\x0f.chord.NodeInfo2\xf3\x01\n\x05\x43hord\x12$\n\x04Ping\x12\x0c.chord.Empty\x1a\x0c.chord.Empty\"\x00\x12\x31\n\rFindSuccessor\x12\r.chord.NodeId\x1a\x0f.chord.NodeInfo\"\x00\x12\x33\n\x10GetSuccessorList\x12\x0c.chord.Empty\x1a\x0f.chord.NodeList\"\x00\x12\x31\n\x0eGetPredecessor\x12\x0c.chord.Empty\x1a\x0f.chord.NodeInfo\"\x00\x12)\n\x06Notify\x12\x0f.chord.NodeInfo\x1a\x0c.chord.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chord_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_NODEID']._serialized_start=31
  _globals['_NODEID']._serialized_end=51
  _globals['_NODEINFO']._serialized_start=53
  _globals['_NODEINFO']._serialized_end=92
  _globals['_NODELIST']._serialized_start=94
  _globals['_NODELIST']._serialized_end=136
  _globals['_CHORD']._serialized_start=139
  _globals['_CHORD']._serialized_end=382
# @@protoc_insertion_point(module_scope)
