# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: models.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'models.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmodels.proto\x12\x06models\"K\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x15\n\rpassword_hash\x18\x04 \x01(\t\"\xb9\x01\n\x04Post\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x11\n\tis_repost\x18\x05 \x01(\x08\x12\x18\n\x10original_post_id\x18\x06 \x01(\t\x12\x1d\n\x15original_post_user_id\x18\x07 \x01(\t\x12\x1f\n\x17original_post_timestamp\x18\x08 \x01(\t\"\x1d\n\tUserPosts\x12\x10\n\x08posts_id\x18\x01 \x03(\t\"\"\n\rUserFollowing\x12\x11\n\tfollowing\x18\x01 \x03(\t\"\"\n\rUserFollowers\x12\x11\n\tfollowers\x18\x01 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=24
  _globals['_USER']._serialized_end=99
  _globals['_POST']._serialized_start=102
  _globals['_POST']._serialized_end=287
  _globals['_USERPOSTS']._serialized_start=289
  _globals['_USERPOSTS']._serialized_end=318
  _globals['_USERFOLLOWING']._serialized_start=320
  _globals['_USERFOLLOWING']._serialized_end=354
  _globals['_USERFOLLOWERS']._serialized_start=356
  _globals['_USERFOLLOWERS']._serialized_end=390
# @@protoc_insertion_point(module_scope)
