# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: posts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'posts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import models_pb2 as models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bposts.proto\x12\x05posts\x1a\x0cmodels.proto\"/\n\x0bPostRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"0\n\x0cPostResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\rRepostRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x18\n\x10original_post_id\x18\x02 \x01(\t\"2\n\x0eRepostResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x0fGetPostsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"/\n\x10GetPostsResponse\x12\x1b\n\x05posts\x18\x01 \x03(\x0b\x32\x0c.models.Post\"$\n\x11GetPostsIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"&\n\x12GetPostsIdResponse\x12\x10\n\x08posts_id\x18\x01 \x03(\t\"!\n\x0eGetPostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\"-\n\x0fGetPostResponse\x12\x1a\n\x04post\x18\x01 \x01(\x0b\x32\x0c.models.Post2\xb2\x02\n\x0bPostService\x12\x32\n\x07Publish\x12\x12.posts.PostRequest\x1a\x13.posts.PostResponse\x12\x35\n\x06Repost\x12\x14.posts.RepostRequest\x1a\x15.posts.RepostResponse\x12;\n\x08GetPosts\x12\x16.posts.GetPostsRequest\x1a\x17.posts.GetPostsResponse\x12\x41\n\nGetPostsId\x12\x18.posts.GetPostsIdRequest\x1a\x19.posts.GetPostsIdResponse\x12\x38\n\x07GetPost\x12\x15.posts.GetPostRequest\x1a\x16.posts.GetPostResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'posts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTREQUEST']._serialized_start=36
  _globals['_POSTREQUEST']._serialized_end=83
  _globals['_POSTRESPONSE']._serialized_start=85
  _globals['_POSTRESPONSE']._serialized_end=133
  _globals['_REPOSTREQUEST']._serialized_start=135
  _globals['_REPOSTREQUEST']._serialized_end=193
  _globals['_REPOSTRESPONSE']._serialized_start=195
  _globals['_REPOSTRESPONSE']._serialized_end=245
  _globals['_GETPOSTSREQUEST']._serialized_start=247
  _globals['_GETPOSTSREQUEST']._serialized_end=281
  _globals['_GETPOSTSRESPONSE']._serialized_start=283
  _globals['_GETPOSTSRESPONSE']._serialized_end=330
  _globals['_GETPOSTSIDREQUEST']._serialized_start=332
  _globals['_GETPOSTSIDREQUEST']._serialized_end=368
  _globals['_GETPOSTSIDRESPONSE']._serialized_start=370
  _globals['_GETPOSTSIDRESPONSE']._serialized_end=408
  _globals['_GETPOSTREQUEST']._serialized_start=410
  _globals['_GETPOSTREQUEST']._serialized_end=443
  _globals['_GETPOSTRESPONSE']._serialized_start=445
  _globals['_GETPOSTRESPONSE']._serialized_end=490
  _globals['_POSTSERVICE']._serialized_start=493
  _globals['_POSTSERVICE']._serialized_end=799
# @@protoc_insertion_point(module_scope)
