# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: relations.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'relations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frelations.proto\x12\trelations\"9\n\rFollowRequest\x12\x13\n\x0b\x66ollower_id\x18\x01 \x01(\t\x12\x13\n\x0b\x66ollowed_id\x18\x02 \x01(\t\"2\n\x0e\x46ollowResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"=\n\x0fUnfollowRequest\x12\x13\n\x0b\x66ollower_id\x18\x01 \x01(\t\x12\x15\n\runfollowed_id\x18\x02 \x01(\t\"4\n\x10UnfollowResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x13GetFollowingRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\")\n\x14GetFollowingResponse\x12\x11\n\tfollowing\x18\x01 \x03(\t\"&\n\x13GetFollowersRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\")\n\x14GetFollowersResponse\x12\x11\n\tfollowers\x18\x01 \x03(\t2\xb8\x02\n\x10RelationsService\x12=\n\x06\x46ollow\x12\x18.relations.FollowRequest\x1a\x19.relations.FollowResponse\x12\x43\n\x08Unfollow\x12\x1a.relations.UnfollowRequest\x1a\x1b.relations.UnfollowResponse\x12O\n\x0cGetFollowing\x12\x1e.relations.GetFollowingRequest\x1a\x1f.relations.GetFollowingResponse\x12O\n\x0cGetFollowers\x12\x1e.relations.GetFollowersRequest\x1a\x1f.relations.GetFollowersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FOLLOWREQUEST']._serialized_start=30
  _globals['_FOLLOWREQUEST']._serialized_end=87
  _globals['_FOLLOWRESPONSE']._serialized_start=89
  _globals['_FOLLOWRESPONSE']._serialized_end=139
  _globals['_UNFOLLOWREQUEST']._serialized_start=141
  _globals['_UNFOLLOWREQUEST']._serialized_end=202
  _globals['_UNFOLLOWRESPONSE']._serialized_start=204
  _globals['_UNFOLLOWRESPONSE']._serialized_end=256
  _globals['_GETFOLLOWINGREQUEST']._serialized_start=258
  _globals['_GETFOLLOWINGREQUEST']._serialized_end=296
  _globals['_GETFOLLOWINGRESPONSE']._serialized_start=298
  _globals['_GETFOLLOWINGRESPONSE']._serialized_end=339
  _globals['_GETFOLLOWERSREQUEST']._serialized_start=341
  _globals['_GETFOLLOWERSREQUEST']._serialized_end=379
  _globals['_GETFOLLOWERSRESPONSE']._serialized_start=381
  _globals['_GETFOLLOWERSRESPONSE']._serialized_end=422
  _globals['_RELATIONSSERVICE']._serialized_start=425
  _globals['_RELATIONSSERVICE']._serialized_end=737
# @@protoc_insertion_point(module_scope)
